//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManager.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceManager.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ####################################
        ///# Akka Actor Reference Config File #
        ///####################################
        ///
        ///# This is the reference config file that contains all the default settings.
        ///# Make your edits/overrides in your application.conf.
        ///
        ///akka {
        ///  # Loggers are created and registered synchronously during ActorSystem
        ///  # start-up, and since they are actors, this timeout is used to bound the
        ///  # waiting time
        ///  logger-startup-timeout = 5s
        ///
        ///  # You can enable asynchronous loggers creation by se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Akka {
            get {
                return ResourceManager.GetString("Akka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####################################
        ///# Akka Cluster Reference Config File #
        ///######################################
        ///
        ///# This is the reference config file that contains all the default settings.
        ///# Make your edits/overrides in your application.conf.
        ///
        ///akka {
        ///
        ///  cluster {
        ///
        ///    # How long to wait for one of the seed nodes to reply to initial join request.
        ///    # When this is the first seed node and there is no positive reply from the other
        ///    # seed nodes within this timeout it will join itself to bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AkkaCluster {
            get {
                return ResourceManager.GetString("AkkaCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###########################################################
        ///# Akka Persistence Extension Reference Configuration File #
        ///###########################################################
        ///
        ///# This is the reference config file that contains all the default settings.
        ///# Make your edits in your application.conf in order to override these settings.
        ///
        ///# Directory of persistence journal and snapshot store plugins is available at the
        ///# Akka.NET Community Projects page http://getakka.net/docs/Community%20Plugins
        ///
        ///#  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AkkaPersistence {
            get {
                return ResourceManager.GetString("AkkaPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####################################
        ///# Akka Remote Reference Config File #
        ///#####################################
        ///
        ///# This is the reference config file that contains all the default settings.
        ///# Make your edits/overrides in your application.conf.
        ///
        ///# comments about akka.actor settings left out where they are already in akka-
        ///# actor.jar, because otherwise they would be repeated in config rendering.
        ///
        ///akka {
        ///
        ///  actor {
        ///
        ///    deployment {
        ///
        ///      default {
        ///
        ///        # if this is set to a valid remo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AkkaRemote {
            get {
                return ResourceManager.GetString("AkkaRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####################################
        ///# Akka Stream Reference Config File #
        ///#####################################
        ///
        ///akka {
        ///  stream {
        ///
        ///    # Default flow materializer settings
        ///    materializer {
        ///
        ///      # Initial size of buffers used in stream elements
        ///	  # Note: If you change this value also change the fallback value in ActorMaterializerSettings
        ///      initial-input-buffer-size = 4
        ///
        ///      # Maximum size of buffers used in stream elements
        ///	  # Note: If you change this value also change the fallb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AkkaStreams {
            get {
                return ResourceManager.GetString("AkkaStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to akka.persistence {
        ///	journal {
        ///		mongodb {
        ///			# qualified type name of the MongoDb persistence journal actor
        ///			class = &quot;Akka.Persistence.MongoDb.Journal.MongoDbJournal, Akka.Persistence.MongoDb&quot;
        ///
        ///			# connection string used for database access
        ///			connection-string = &quot;&quot;
        ///
        ///			# should corresponding journal table&apos;s indexes be initialized automatically
        ///			auto-initialize = on
        ///
        ///			# dispatcher used to drive journal actor
        ///			plugin-dispatcher = &quot;akka.actor.default-dispatcher&quot;
        ///
        ///			# MongoDb collectio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseConfig {
            get {
                return ResourceManager.GetString("BaseConfig", resourceCulture);
            }
        }
    }
}
